import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';

import {
  Calendar,
  Conversation,
  ConversationMessage,
  ConversationSummary,
  Device,
  NotificationRule,
  NotificationStrategy,
  PendingQuestion,
  RecurrenceRule,
  ScheduledNotification,
  Task,
  TaskGroup,
  TaskOccurrenceException,
  TelegramLink,
  User,
  UserMemoryFact,
} from './entities';
import {
  CalendarRepository,
  ConversationMessageRepository,
  ConversationRepository,
  ConversationSummaryRepository,
  DeviceRepository,
  NotificationRuleRepository,
  NotificationStrategyRepository,
  PendingQuestionRepository,
  RecurrenceRuleRepository,
  ScheduledNotificationRepository,
  TaskGroupRepository,
  TaskOccurrenceExceptionRepository,
  TaskRepository,
  TelegramLinkRepository,
  UserMemoryFactRepository,
  UserRepository,
} from './repositories';
import {
  CalendarDatabaseService,
  ConversationDatabaseService,
  ConversationMessageDatabaseService,
  ConversationSummaryDatabaseService,
  DeviceDatabaseService,
  NotificationRuleDatabaseService,
  NotificationStrategyDatabaseService,
  PendingQuestionDatabaseService,
  RecurrenceRuleDatabaseService,
  ScheduledNotificationDatabaseService,
  TaskDatabaseService,
  TaskGroupDatabaseService,
  TaskOccurrenceExceptionDatabaseService,
  TelegramLinkDatabaseService,
  UserDatabaseService,
  UserMemoryFactDatabaseService,
} from './services';

/**
 * Database module that registers every Cue entity with TypeORM and wires the repository
 * and database-service pairs that feature modules consume. Direct use of repositories
 * or entities outside this module is intentionally discouraged — all access flows through
 * the exported database services.
 */
@Module({
  imports: [
    TypeOrmModule.forFeature([
      User,
      Device,
      TelegramLink,
      Calendar,
      TaskGroup,
      Task,
      RecurrenceRule,
      TaskOccurrenceException,
      NotificationStrategy,
      NotificationRule,
      ScheduledNotification,
      Conversation,
      ConversationMessage,
      ConversationSummary,
      UserMemoryFact,
      PendingQuestion,
    ]),
  ],
  providers: [
    UserRepository,
    DeviceRepository,
    TelegramLinkRepository,
    CalendarRepository,
    TaskGroupRepository,
    TaskRepository,
    RecurrenceRuleRepository,
    TaskOccurrenceExceptionRepository,
    NotificationStrategyRepository,
    NotificationRuleRepository,
    ScheduledNotificationRepository,
    ConversationRepository,
    ConversationMessageRepository,
    ConversationSummaryRepository,
    UserMemoryFactRepository,
    PendingQuestionRepository,
    UserDatabaseService,
    DeviceDatabaseService,
    TelegramLinkDatabaseService,
    CalendarDatabaseService,
    TaskGroupDatabaseService,
    TaskDatabaseService,
    RecurrenceRuleDatabaseService,
    TaskOccurrenceExceptionDatabaseService,
    NotificationStrategyDatabaseService,
    NotificationRuleDatabaseService,
    ScheduledNotificationDatabaseService,
    ConversationDatabaseService,
    ConversationMessageDatabaseService,
    ConversationSummaryDatabaseService,
    UserMemoryFactDatabaseService,
    PendingQuestionDatabaseService,
  ],
  exports: [
    UserDatabaseService,
    DeviceDatabaseService,
    TelegramLinkDatabaseService,
    CalendarDatabaseService,
    TaskGroupDatabaseService,
    TaskDatabaseService,
    RecurrenceRuleDatabaseService,
    TaskOccurrenceExceptionDatabaseService,
    NotificationStrategyDatabaseService,
    NotificationRuleDatabaseService,
    ScheduledNotificationDatabaseService,
    ConversationDatabaseService,
    ConversationMessageDatabaseService,
    ConversationSummaryDatabaseService,
    UserMemoryFactDatabaseService,
    PendingQuestionDatabaseService,
  ],
})
export class DatabaseModule {}
