import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';

import {
  Calendar,
  Conversation,
  ConversationMessage,
  ConversationSummary,
  Device,
  NotificationRule,
  NotificationStrategy,
  PendingQuestion,
  PersonaPrompt,
  ScheduledNotification,
  Task,
  TaskGroup,
  TaskOccurrenceException,
  TelegramLink,
  User,
  UserBriefSettings,
  UserMemoryFact,
  UserReportSettings,
  UserSyncState,
} from './entities';
import {
  CalendarRepository,
  ConversationMessageRepository,
  ConversationRepository,
  ConversationSummaryRepository,
  DeviceRepository,
  NotificationRuleRepository,
  NotificationStrategyRepository,
  PendingQuestionRepository,
  PersonaPromptRepository,
  ScheduledNotificationRepository,
  TaskGroupRepository,
  TaskOccurrenceExceptionRepository,
  TaskRepository,
  TelegramLinkRepository,
  UserBriefSettingsRepository,
  UserMemoryFactRepository,
  UserReportSettingsRepository,
  UserRepository,
  UserSyncStateRepository,
} from './repositories';
import {
  CalendarDatabaseService,
  ConversationDatabaseService,
  ConversationMessageDatabaseService,
  ConversationSummaryDatabaseService,
  DeviceDatabaseService,
  NotificationRuleDatabaseService,
  NotificationStrategyDatabaseService,
  PendingQuestionDatabaseService,
  PersonaPromptDatabaseService,
  ScheduledNotificationDatabaseService,
  TaskDatabaseService,
  TaskGroupDatabaseService,
  TaskOccurrenceExceptionDatabaseService,
  TelegramLinkDatabaseService,
  UserBriefSettingsDatabaseService,
  UserDatabaseService,
  UserMemoryFactDatabaseService,
  UserReportSettingsDatabaseService,
  UserSyncStateDatabaseService,
} from './services';

/**
 * Database module that registers every Cue entity with TypeORM and wires the repository
 * and database-service pairs that feature modules consume. Direct use of repositories
 * or entities outside this module is intentionally discouraged — all access flows through
 * the exported database services.
 */
@Module({
  imports: [
    TypeOrmModule.forFeature([
      User,
      Device,
      TelegramLink,
      Calendar,
      TaskGroup,
      Task,
      TaskOccurrenceException,
      NotificationStrategy,
      NotificationRule,
      ScheduledNotification,
      Conversation,
      ConversationMessage,
      ConversationSummary,
      UserMemoryFact,
      PendingQuestion,
      UserReportSettings,
      UserBriefSettings,
      PersonaPrompt,
      UserSyncState,
    ]),
  ],
  providers: [
    UserRepository,
    DeviceRepository,
    TelegramLinkRepository,
    CalendarRepository,
    TaskGroupRepository,
    TaskRepository,
    TaskOccurrenceExceptionRepository,
    NotificationStrategyRepository,
    NotificationRuleRepository,
    ScheduledNotificationRepository,
    ConversationRepository,
    ConversationMessageRepository,
    ConversationSummaryRepository,
    UserMemoryFactRepository,
    PendingQuestionRepository,
    UserReportSettingsRepository,
    UserBriefSettingsRepository,
    PersonaPromptRepository,
    UserSyncStateRepository,
    UserDatabaseService,
    DeviceDatabaseService,
    TelegramLinkDatabaseService,
    CalendarDatabaseService,
    TaskGroupDatabaseService,
    TaskDatabaseService,
    TaskOccurrenceExceptionDatabaseService,
    NotificationStrategyDatabaseService,
    NotificationRuleDatabaseService,
    ScheduledNotificationDatabaseService,
    ConversationDatabaseService,
    ConversationMessageDatabaseService,
    ConversationSummaryDatabaseService,
    UserMemoryFactDatabaseService,
    PendingQuestionDatabaseService,
    UserReportSettingsDatabaseService,
    UserBriefSettingsDatabaseService,
    PersonaPromptDatabaseService,
    UserSyncStateDatabaseService,
  ],
  exports: [
    UserDatabaseService,
    DeviceDatabaseService,
    TelegramLinkDatabaseService,
    CalendarDatabaseService,
    TaskGroupDatabaseService,
    TaskDatabaseService,
    TaskOccurrenceExceptionDatabaseService,
    NotificationStrategyDatabaseService,
    NotificationRuleDatabaseService,
    ScheduledNotificationDatabaseService,
    ConversationDatabaseService,
    ConversationMessageDatabaseService,
    ConversationSummaryDatabaseService,
    UserMemoryFactDatabaseService,
    PendingQuestionDatabaseService,
    UserReportSettingsDatabaseService,
    UserBriefSettingsDatabaseService,
    PersonaPromptDatabaseService,
    UserSyncStateDatabaseService,
  ],
})
export class DatabaseModule {}
